name: Build&Tests
run-name: ${{ github.actor }} created PR ${{ github.ref_name }} build and tests are about to start
env:
  API_URL: ${{ secrets.API_URL }}
  GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
on:
  pull_request:
jobs:
  test_with_coverage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build started."
      - name: Checkout the code
        uses: actions/checkout@v3
      - run: echo apiUrl=\"$API_URL\" > ./secret.properties
      - run: echo $GOOGLE_SERVICES > ./app/google-services.json
      - name: Build the app
        run: ./gradlew testDebugUnitTest jacocoAndroidTestReport
      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          token: ${{ secrets.TOKEN_GITHUB }}
          min-coverage-overall: 0
          min-coverage-changed-files: 60