name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
env:
  API_URL: ${{ secrets.API_URL }}
  GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout the code
        uses: actions/checkout@v2
      - run: echo apiUrl=\"$API_URL\" > ./secret.properties
      - run: echo GOOGLE_SERVICES > ./app/google-services.json
      - name: Build the app
        run: ./gradlew build