name: default

on:
  push:
    branches:
      - "*"

jobs:
  steps:
    - name: GET_API_URL
        env:
          somecredentiaosl: ${{secrets.API_URL}}
        run: echo API_URL=\"apiUrl\" > ./secret.properties