name: default

on:
  push:
    branches:
      - "*"

jobs:
  steps:
    - name: GET_API_URL
        env:
          apiUrl: ${{ secrets.API_URL }}
        run: echo apiUrl=\"apiUrl\" > ./secret.properties